<script type="text/javascript">
window.location.href = 'http://localhost/Task/index.php';
</script>
<?php

include('connect.php');

$sql = "SELECT tname, detail, email, deadline, task.username FROM task, registration where (deadline = CURRENT_DATE or deadline = CURRENT_DATE+1) and task.username = registration.username;";
$result = mysqli_query($conn, $sql);
require 'PHPMailerAutoload.php';
if ($result->num_rows > 0) {
    while($row = $result->fetch_assoc()) {
        $mail = new PHPMailer;

        $mail->SMTPDebug = 4;                               // Enable verbose debug output
        
        $mail->isSMTP();                                      // Set mailer to use SMTP
        $mail->Host = 'smtp.gmail.com';                       // Specify main and backup SMTP servers
        $mail->SMTPAuth = true;                               // Enable SMTP authentication
        $mail->Username = 'multitaskscheduler@gmail.com';                 // SMTP username
        $mail->Password = 'kjsceinternship';                           // SMTP password
        $mail->SMTPSecure = 'tls';                            // Enable TLS encryption, `ssl` also accepted
        $mail->Port = 587;                                    // TCP port to connect to
        
        $mail->setFrom('multitaskscheduler@gmail.com', 'Planning Buddy');
        $mail->addAddress($row['email']);     // Add a recipient
        
        $mail->Subject = "Reminder for ".$row['tname'];
        $mail->Body    = "Hi there!<br><br>  It's your Task Scheduler ".$row['username'].",<br>Your task : ".$row['tname']." is due!<br>Task Description: ".$row['detail']."<br><br>Don't reply to this mail. They are really autogenerated  ;-)<br><br>With love,<br>Your precise scheduler.";
        $mail->AltBody = "You have the task".$row['tname']." due! Complete it soon :)";
        
        if(!$mail->send()) {
            echo 'Message could not be sent.';
            echo 'Mailer Error: ' . $mail->ErrorInfo;
        } else {
            echo 'Message has been sent';
        }
    }
} 



$sql = "UPDATE task deadline = CURRENT_DATE+7 where label=4";
$result = mysqli_query($conn, $sql);
$conn -> close();
?>